import { test, expect } from '@playwright/test';

test('map navigation, profile, membership interest, and persistence', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'inhabit', exact: true }).click();
  await page.getByRole('button', { name: /Thermal Circuits/ }).click();
  await expect(page.getByRole('heading', { name: 'cc directory' })).toBeVisible();
  await expect(page.getByLabel('Category', { exact: true })).toHaveValue('SPA');
  await page.getByRole('button', { name: 'View plan', exact: true }).click();
  await page.getByRole('button', { name: 'Save my interest' }).click();
  await expect(page.getByRole('button', { name: 'Manage saved plan' })).toBeVisible();
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await page.getByLabel('Display name').fill('Alex');
  await page.getByLabel('City or neighborhood').fill('Lagos');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Manage saved plan' })).toBeVisible();
  await page.getByRole('button', { name: 'Your profile', exact: true }).click();
  await expect(page.getByLabel('Display name')).toHaveValue('Alex');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('Your location', { exact: true }).fill('Lagos');
  await page.getByRole('button', { name: 'Search nearby' }).click();
  await expect(page.getByRole('alert')).toContainText('not configured');
  expect(errors).toEqual([]);
});

test('vault create, rate, edit, filter, export, import, and delete', async ({ page }) => {
  await page.goto('/#collection/LIBRARY');
  await page.getByRole('button', { name: '+ Add item', exact: true }).click();
  await page.getByLabel('Book title').fill('The Hobbit');
  await page.getByLabel('Author', { exact: true }).fill('J. R. R. Tolkien');
  await page.getByRole('button', { name: 'Save item' }).click();
  await page.getByLabel('Status of The Hobbit').selectOption('read');
  await page.getByRole('button', { name: 'Rate The Hobbit 4 stars' }).click();
  await page.getByLabel('Mark available to let', { exact: true }).check();
  await page.getByRole('button', { name: 'Memberships', exact: true }).click();
  await page.getByRole('button', { name: 'Vault', exact: true }).click();
  await page.reload();
  await expect(page.getByLabel('Status of The Hobbit')).toHaveValue('read');
  await expect(page.getByRole('button', { name: 'Rate The Hobbit 4 stars' })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Book title').fill('The Hobbit - revised');
  await page.getByRole('button', { name: 'Save item' }).click();
  await page.getByRole('button', { name: 'Preview collection' }).click();
  await expect(page.getByRole('dialog')).toContainText('The Hobbit - revised');
  await page.keyboard.press('Escape');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export vault' }).click();
  const file = await download;
  expect(file.suggestedFilename()).toBe('cclo-vault.json');
  const backup = await file.path();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByRole('button', { name: 'Delete item', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Make this vault yours' })).toBeVisible();
  await page.getByLabel('Import vault backup', { exact: true }).setInputFiles(backup!);
  await expect(page.getByRole('heading', { name: 'The Hobbit - revised', exact: true })).toBeVisible();
  await page.getByLabel('Search vault').fill('missing title');
  await expect(page.getByRole('heading', { name: 'No matching items' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await expect(page.getByRole('heading', { name: 'The Hobbit - revised', exact: true })).toBeVisible();
});

test('mobile map, photo fallback, category isolation, and layout', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto('/');
  await page.getByRole('button', { name: 'concierge', exact: true }).click();
  await page.getByRole('button', { name: /Fragrance Vault/ }).click();
  await expect(page.getByRole('button', { name: /cconsort/ })).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Upload collection photo', { exact: true }).setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN1cAAAAASUVORK5CYII=', 'base64') });
  await page.getByLabel('Fragrance name').fill('Sample scent');
  await page.getByLabel('Brand', { exact: true }).fill('Sample brand');
  await page.getByRole('button', { name: 'Save item' }).click();
  await expect(page.getByRole('heading', { name: 'Sample scent', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: /ccmuseo/ }).click();
  await expect(page.getByRole('heading', { name: 'Make this vault yours' })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'Sample scent', exact: true })).toBeVisible();
});
